version: 1.6.2-{build}-{branch}
os: Visual Studio 2015

configuration: Release



before_build:
- git config user.email "you@example.com"
- git config user.name "user"
- git submodule update --init --recursive
- mkdir LiveSplit\LiveSplit.Core\Updates\GitInfo
- git describe --dirty --always --long --tags > LiveSplit\LiveSplit.Core\Updates\GitInfo\version.txt
- git rev-parse --abbrev-ref HEAD > LiveSplit\LiveSplit.Core\Updates\GitInfo\branch.txt
- git rev-parse HEAD > LiveSplit\LiveSplit.Core\Updates\GitInfo\revision.txt

build_script:
- msbuild LiveSplit\LiveSplit.sln /verbosity:minimal /p:NoWarn=1591 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test:
  assemblies: LiveSplit\LiveSplit.Tests\bin\Release\LiveSplit.Tests.dll

after_build:
- ps: >-
    if (!"$env:APPVEYOR_PULL_REQUEST_TITLE" -and ("$env:APPVEYOR_REPO_BRANCH" -eq "master"))
    {
        $BUILD_NAME = "LiveSplitDevBuild.zip"

        mkdir .\LiveSplit\bin\Release\Resources

        cp .\LiveSplit\Resources\SplitsFile.ico .\LiveSplit\bin\Release\Resources\

        cp .\LiveSplit\Resources\LayoutFile.ico .\LiveSplit\bin\Release\Resources\

        cd LiveSplit\bin\Release

        Get-ChildItem * -Include *.xml -Recurse | Remove-Item

        Get-ChildItem * -Include *.pdb -Recurse | Remove-Item

        cd ..\..\..\

        7z a $BUILD_NAME .\LiveSplit\bin\Release\*


        # Download winscp

        Invoke-WebRequest "http://livesplit.org/winscp577.zip" -OutFile "winscp577.zip"

        7z e -y winscp577.zip

        # Upload to server

        .\WinSCP.com /command `
            "option batch abort" `
            "option confirm off" `
            "open ftp://bruger:kodekode@vocaboo.hostedftp.com -hostkey=*" `
            "put $BUILD_NAME /" `
            "exit"
    }
